<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3M9NET2" name="com.sonatype.console.selenium.LoadTestScenario" tests="9" failures="0" timestamp="13 Dec 2019 08:31:31 GMT" time="11.972" errors="1">
  <testcase name="testcase6" time="0.297" classname="com.sonatype.console.selenium.LoadTestScenario"/>
  <testcase name="testcase8" time="2.611" classname="com.sonatype.console.selenium.LoadTestScenario"/>
  <testcase name="testcase1" time="3.277" classname="com.sonatype.console.selenium.LoadTestScenario"/>
  <testcase name="testcase2" time="4.298" classname="com.sonatype.console.selenium.LoadTestScenario"/>
  <testcase name="testcase5" time="0.286" classname="com.sonatype.console.selenium.LoadTestScenario"/>
  <testcase name="testcase0" time="0.001" classname="com.sonatype.console.selenium.LoadTestScenario">
    <error type="org.testng.SkipException" message="Skipping the test case">
      <![CDATA[org.testng.SkipException: Skipping the test case
	at com.sonatype.console.selenium.LoadTestScenario.testcase0(LoadTestScenario.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- testcase0 -->
  <testcase name="testcase7" time="0.537" classname="com.sonatype.console.selenium.LoadTestScenario"/>
  <testcase name="testcase4" time="0.341" classname="com.sonatype.console.selenium.LoadTestScenario"/>
  <testcase name="testcase3" time="0.324" classname="com.sonatype.console.selenium.LoadTestScenario"/>
</testsuite> <!-- com.sonatype.console.selenium.LoadTestScenario -->
